# This file was generated by GoReleaser. DO NOT EDIT.
cask "devassist" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "b91bd45cda73d2345cd2f03f24140285ce534825a5cda9010a0f5e8b54f8a5b5"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3d28a2119eefe913c36f484637af5c475f67a6af2fdd798c68e0bb2b9a4d12a"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "07f1458d8ee9a9e2625ed5c59c00dcf3e229a5a6e04b41293b2aa080f1163b6a"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32208d36a867a9ea0612e01774495f53e6eb1c0cf934a7c9e82b5d462ed94909"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devassist"
  desc "Your pull requests and tickets in one place, with an agent you can put to work on them"
  homepage "https://github.com/franbach/devassist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devassist"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devassist"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `devassist setup` once, then `devassist doctor` to check what it found.

    DevAssist drives an agent CLI you already have — install claude
    (https://claude.com/claude-code) or codex, or point `agents:` at another.
  EOS
end
