# This file was generated by GoReleaser. DO NOT EDIT.
cask "devassist" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "f494bb1978637faad984b2f81ce035a2a659884961ab0cbcf956cbab23775d0a"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "88213bf2a3bd9ef80e1b323a30b4cbaf65721fdb986fffa368c986eb0908ba9c"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "06dd767b1dc5a49049e077b33ee92bbd0a3a47c498067354ecb66a9702881745"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "397017539fb4d59bac9c41f4ce9b1dec9932074cdff3561a24d7800dd89dcb78"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devassist"
  desc "Your pull requests and tickets in one place, with an agent you can put to work on them"
  homepage "https://github.com/franbach/devassist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devassist"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devassist"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `devassist setup` once, then `devassist doctor` to check what it found.

    DevAssist drives an agent CLI you already have — install claude
    (https://claude.com/claude-code) or codex, or point `agents:` at another.
  EOS
end
