# This file was generated by GoReleaser. DO NOT EDIT.
cask "devassist" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "62b6ac64639a13ad9f3d69b3fba2956292976a37df84f894544e962bcf33afb3"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0c1adb72664c042baca9e95e9c3b4ae41a0578ec0eb7d69eb46c2031b55d8b4"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3758853b771d30f87f71204e1437ae3326a2dd49cd8c67a040e459f34d5bfc3f"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ed5896e3dbd59fbaf3bbdb0d58b7b3bb74e8d7fcaf0e82b1fdc3c1dce9c32f2"
      url "https://github.com/franbach/devassist/releases/download/v#{version}/devassist_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devassist"
  desc "Your pull requests and tickets in one place, with an agent you can put to work on them"
  homepage "https://github.com/franbach/devassist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devassist"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devassist"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `devassist setup` once, then `devassist doctor` to check what it found.

    DevAssist drives an agent CLI you already have — install claude
    (https://claude.com/claude-code) or codex, or point `agents:` at another.
  EOS
end
